# Generated by Django 4.1.7 on 2023-03-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstock',
            name='batch_no',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
