# Generated by Django 4.1.7 on 2023-04-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0022_alter_reservationbilldetails_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdetails',
            name='status',
            field=models.CharField(default='booked', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservationroomdetails',
            name='status',
            field=models.CharField(default='booked', max_length=20),
        ),
    ]
