# Generated by Django 4.1.7 on 2023-04-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0024_alter_guestcheckincheckoutdetails_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationbilldetails',
            name='is_amount_paid',
            field=models.BooleanField(default=False),
        ),
    ]
